/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import Adiciona.Adiciona_Carro;
import Editar.Edit_Carro;
import Editar.SelecionarTipo;
import Locadora.Repositorio;
import static Main.main.rep;
import PacClientes.Cliente;
import java.io.File;
import static java.lang.String.format;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author leonardo
 */
public class FrameMenu extends javax.swing.JFrame {

    static Repositorio rep = new Repositorio();

    /**
     * Creates new form FrameMenu
     */
    public FrameMenu() {
        try {
            rep.lerArquivo("ClienteFisico.csv");
            rep.lerArquivo("ClienteJuridico.csv");
            rep.lerArquivo("Carro.csv");
            rep.lerArquivo("Contrato.csv");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
        initComponents();
    }

    public FrameMenu(Repositorio rep) {
        this.rep = rep;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Alugar = new javax.swing.JButton();
        AddCarro = new javax.swing.JButton();
        Sair = new javax.swing.JButton();
        Contratos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Remover = new javax.swing.JButton();
        Editar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Alugar.setText("Alugar Carro");
        Alugar.setPreferredSize(new java.awt.Dimension(150, 40));
        Alugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlugarActionPerformed(evt);
            }
        });

        AddCarro.setText("Adicionar Carro");
        AddCarro.setPreferredSize(new java.awt.Dimension(120, 40));
        AddCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCarroActionPerformed(evt);
            }
        });

        Sair.setText("Sair");
        Sair.setPreferredSize(new java.awt.Dimension(120, 40));
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });

        Contratos.setText("Contratos");
        Contratos.setPreferredSize(new java.awt.Dimension(120, 40));
        Contratos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContratosActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("WenQuanYi Micro Hei Mono", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bem-vindos!");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(12, 5, 5)));
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 70));

        Remover.setText("Remover");
        Remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoverActionPerformed(evt);
            }
        });

        Editar.setText("Editar");
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Remover, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Alugar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AddCarro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Contratos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(74, 265, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(Alugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Contratos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Remover, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Sair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        try {
            rep.escreverArquivo("Carro.csv");
            rep.escreverArquivo("ClienteFisico.csv");
            rep.escreverArquivo("ClienteJuridico.csv");
            rep.escreverArquivo("Contrato.csv");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
        System.exit(1);
    }//GEN-LAST:event_SairActionPerformed

    private void AlugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlugarActionPerformed
        int opcao = JOptionPane.showConfirmDialog(rootPane, "Ja possui cadastro?");
        if (opcao == 0) {
            this.dispose();
            try {
                new BuscaCliente(rep).setVisible(true);
            } catch (ParseException ex) {
                Logger.getLogger(FrameMenu.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (opcao == 1) {
            this.dispose();
            new TipoCliente(rep).setVisible(true);
        } else {
            this.dispose();
            new FrameMenu(rep).setVisible(true);
        }
    }//GEN-LAST:event_AlugarActionPerformed

    private void AddCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCarroActionPerformed
        this.dispose();
        try {
            new Adiciona_Carro(rep).setVisible(true);
        }catch (Exception e){
            
        }
    }//GEN-LAST:event_AddCarroActionPerformed

    private void ContratosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContratosActionPerformed
        this.dispose();
        new Mostrar_Contratos(rep).setVisible(true);
    }//GEN-LAST:event_ContratosActionPerformed

    private void RemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoverActionPerformed
        this.dispose();
        try {
            new Remover(rep).setVisible(true);
        } catch (Exception e) {

        }
    }//GEN-LAST:event_RemoverActionPerformed

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed
        try {
            this.dispose();
            new SelecionarTipo(rep).setVisible(true);
        }catch (Exception e){
            
        }
    }//GEN-LAST:event_EditarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCarro;
    private javax.swing.JButton Alugar;
    private javax.swing.JButton Contratos;
    private javax.swing.JButton Editar;
    private javax.swing.JButton Remover;
    private javax.swing.JButton Sair;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
